lib/pt_checker_web/router.ex
defmodule PtCheckerWeb.Router do
  use PtCheckerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PtCheckerWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/routes", RoutesController, only: [:index, :show]
  end

  # Other scopes may use custom stacks.
  # scope "/api", PtCheckerWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: PtCheckerWeb.Telemetry
    end
  end
end

lib/pt_checker/route.ex
defmodule PtChecker.Route do
  use Ecto.Schema
  import Ecto.Changeset

  schema "routes" do
    field :ref, :string
    field :message_level, :string
    field :result, PtChecker.Result.Term
    timestamps()
  end

  @doc false
  def changeset(route, attrs) do
    route
    |> cast(attrs, [:ref, :message_level, :result])
    |> validate_required([])
  end
end

lib/pt_checker/routes.ex
defmodule PtChecker.Routes do
  alias PtChecker.Route
  alias PtChecker.Repo
  import Ecto.Query, only: [from: 2]

  @doc """
  Updates route (group) data from remote server and stores its
  validation result
  """
  def update(relation_id) do
    route = Repo.get! Route, relation_id
    dataset = PtChecker.Fetch.fetch(relation_id)
    result = PtChecker.Checker.check_group_root(dataset, relation_id)

    Route.changeset(route, %{result: result}) |> Repo.update!()
  end

  def summary() do
    query = from r in "routes", select: %{id: r.id, ref: r.ref}
    Repo.all(query)
  end

  def route(id) do
    Repo.get! Route, id
  end
end

lib/pt_checker_web/controllers/routes_controller.ex
defmodule PtCheckerWeb.RoutesController do
  use PtCheckerWeb, :controller

  def index(conn, _params) do
    routes = PtChecker.Routes.summary()
    render(conn, "index.html", routes: routes)
  end

  def show(conn, params) do
    route = PtChecker.Routes.route(params["id"])
    render(conn, "show.html", route: route, result: route.result)
  end
end

lib/pt_checker_web/views/routes_view.ex
defmodule PtCheckerWeb.RoutesView do
  use PtCheckerWeb, :view
  alias PtChecker.Result.GroupResult

  def route_ways_js(%GroupResult{route_results: route_results}) do
    data =
      route_results
      |> Enum.map(fn result ->
        result.ways_coords
        |> Enum.map(fn sequence ->
          sequence
          |> Enum.map(fn {lat, lon} ->
            [lat, lon]
          end)
        end)
      end)

    Poison.encode!(data)
  end
end

lib/pt_checker_web/templates/routes/_messages.html.eex
<ul class="validation-messages">
  <%= for {message_id, severity, references} <- @messages do %>
  <li class="validation-messages__message">
    <span class="validation-messages__level validation-messages__level--<%= severity %>"><%= severity %></span>
    <%= PtChecker.Messages.message_title message_id %>
    <code class="validation-messages__id"><%= message_id %></code>
    <%= for reference <- references do %>
    <%= reference %>
    <% end %>
  </li>
  <% end %>
</ul>

lib/pt_checker_web/templates/routes/_tags.html.eex
<table class="osm-tags">
  <tbody>
    <%= for {k, v} <- @tags do %>
    <tr>
      <td class="osm-tags__key"><%= k %></td>
      <td class="osm-tags__value"><%= v %></td>
    </tr>
    <% end %>
  </tbody>
</table>

lib/pt_checker_web/templates/routes/index.html.eex
<%= for route <- @routes do %>
<a href="<%= Routes.routes_path(@conn, :show, route.id) %>">
  <div><%= route.ref %></div>
</a>
<% end %>

lib/pt_checker_web/templates/routes/show.html.eex
<h1>Route</h1>

<section id="tags">
  <h2>Tags</h2>

  <%= if @result.master_tags do %>
  <section>
    <h3>Route master, <%= @result.relation_id %></h3>

    <%= render "_tags.html", tags: @result.master_tags %>
  </section>
  <% end %>

  <%= for %{tags: tags, relation_id: relation_id} <- @result.route_results do %>
  <section>
    <h3>Route <%= relation_id %></h3>

    <%= render "_tags.html", tags: tags %>
  </section>
  <% end %>
</section>

<section id="messages">
  <h2>Validation messages</h2>

  <%= if @result.master_messages && @result.master_messages != [] do %>
  <section>
    <h3>Route master</h3>

    <%= render "_messages.html", messages: @result.master_messages %>
  </section>
  <% end %>

  <%= for %{messages: messages, relation_id: relation_id} <- @result.route_results do %>
  <section>
    <h3>Route <%= relation_id %></h3>

    <%= render "_messages.html", messages: messages %>
  </section>
  <% end %>
</section>

<section id="map">
</section>

<script>
 window.route_ways = <%= route_ways_js(@result) %>
</script>